stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    params:
    - data_preprocessing.test_size
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    outs:
    - data/processed
    - models/feature_transformer.pkl

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - data/processed
      - src/model/model_building.py
    params:
      - model.n_estimators
      - model.max_depth
      - model.learning_rate
      - model.subsample
      - model.colsample_bytree
      - model.reg_alpha
      - model.reg_lambda
      - model.random_state
      - model.tree_method
      - model.device
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json
    # outs:
    # - reports/experiment_info.json # It is already tracked by git so no need to add here

  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - reports/experiment_info.json
    - src/model/register_model.py